In [1]:
import pandas as pd
import numpy as np

In [3]:
pd.options.display.float_format='{:.2f}'.format
np.set_printoptions(precision=2)

In [14]:
x1 = np.random.rand(2,5)*10
x1

array([[7.89, 6.57, 6.97, 8.16, 3.36],
       [5.52, 4.05, 6.  , 7.22, 9.3 ]])

In [15]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.69, -0.14, -0.21, -0.1 , -0.76],
       [-0.3 , -0.18, -0.88, -0.83, -0.61]])

In [16]:
np.concatenate([x1,x2])

array([[ 7.89,  6.57,  6.97,  8.16,  3.36],
       [ 5.52,  4.05,  6.  ,  7.22,  9.3 ],
       [-0.69, -0.14, -0.21, -0.1 , -0.76],
       [-0.3 , -0.18, -0.88, -0.83, -0.61]])

In [17]:
np.concatenate([x1,x2]).shape

(4, 5)

In [18]:
np.concatenate([x1,x2], axis=1)

array([[ 7.89,  6.57,  6.97,  8.16,  3.36, -0.69, -0.14, -0.21, -0.1 ,
        -0.76],
       [ 5.52,  4.05,  6.  ,  7.22,  9.3 , -0.3 , -0.18, -0.88, -0.83,
        -0.61]])

In [19]:
np.concatenate([x1,x2], axis=1).shape

(2, 10)

In [21]:
s1 = pd.Series(x1[0], index=['a','b','c','d','e'])
s1

a   7.89
b   6.57
c   6.97
d   8.16
e   3.36
dtype: float64

In [23]:
s2 = pd.Series(x2[0], index=['c','d','e','f','g'])
s2

c   -0.69
d   -0.14
e   -0.21
f   -0.10
g   -0.76
dtype: float64

In [25]:
pd.concat([s1,s2], axis=1)

0     1
a 7.89   NaN
b 6.57   NaN
c 6.97 -0.69
d 8.16 -0.14
e 3.36 -0.21
f  NaN -0.10
g  NaN -0.76

In [26]:
s1.reset_index(drop=True)

0   7.89
1   6.57
2   6.97
3   8.16
4   3.36
dtype: float64

In [27]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0 7.89 -0.69
1 6.57 -0.14
2 6.97 -0.21
3 8.16 -0.10
4 3.36 -0.76

In [29]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b'])
df1

a    b
0 5.81 3.14
1 1.98 3.89
2 4.30 5.92

In [30]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a','b'], index=[2,3,4])
df2

a     b
2 -0.66 -0.48
3 -0.78 -0.71
4 -0.72 -0.33

In [32]:
pd.concat([df1,df2])

a     b
0  5.81  3.14
1  1.98  3.89
2  4.30  5.92
2 -0.66 -0.48
3 -0.78 -0.71
4 -0.72 -0.33

In [33]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 5.81 3.14   NaN   NaN
1 1.98 3.89   NaN   NaN
2 4.30 5.92 -0.66 -0.48
3  NaN  NaN -0.78 -0.71
4  NaN  NaN -0.72 -0.33

In [34]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
2 4.30 5.92 -0.66 -0.48

In [35]:
pd.concat([df1.reset_index(drop=True),df2.reset_index(drop=True)], axis=1)

a    b     a     b
0 5.81 3.14 -0.66 -0.48
1 1.98 3.89 -0.78 -0.71
2 4.30 5.92 -0.72 -0.33

In [36]:
df1.append(df2)

a     b
0  5.81  3.14
1  1.98  3.89
2  4.30  5.92
2 -0.66 -0.48
3 -0.78 -0.71
4 -0.72 -0.33

In [37]:
df1.append(df2).append(df2)

a     b
0  5.81  3.14
1  1.98  3.89
2  4.30  5.92
2 -0.66 -0.48
3 -0.78 -0.71
4 -0.72 -0.33
2 -0.66 -0.48
3 -0.78 -0.71
4 -0.72 -0.33

In [38]:
df1.T

0    1    2
a 5.81 1.98 4.30
b 3.14 3.89 5.92

In [39]:
df1.T.append(df2.T).T

a    b     a     b
0 5.81 3.14   NaN   NaN
1 1.98 3.89   NaN   NaN
2 4.30 5.92 -0.66 -0.48
3  NaN  NaN -0.78 -0.71
4  NaN  NaN -0.72 -0.33